package org.ual.hmis.GallardoMartinez;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
public class LoginIncorrectoFaltaContraseaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  private WebDriverWait wait;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	    System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe"); 
	    System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
	   
	    
//	    FirefoxOptions firefoxOptions = new FirefoxOptions(); 
//	    firefoxOptions.addArguments("-headless");
//	    driver = new FirefoxDriver(firefoxOptions);	  
//	    
	    
	    

	    ChromeOptions chromeOptions = new ChromeOptions(); 
	    chromeOptions.addArguments("-headless");
	    driver = new ChromeDriver(chromeOptions);
	    // WebDriver driver = new HtmlUnitDriver(BrowserVersion.FIREFOX, true);

	    
    wait = new WebDriverWait(driver, Duration.ofSeconds(30));

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginIncorrectoFaltaContrasea() {
    // Test name: LoginIncorrectoFaltaContraseña
    // Step # | name | target | value
    // 1 | open | /login | 
    driver.get("https://my-app-1748620076153.azurewebsites.net/login/login");
    // 2 | setWindowSize | 1670x697 | 
    driver.manage().window().setSize(new Dimension(1670, 697));
    // 3 | click | id=input-vaadin-text-field-7 | 
    wait.until(ExpectedConditions.elementToBeClickable(By.id("input-vaadin-text-field-7")));

    driver.findElement(By.id("input-vaadin-text-field-7")).click();
    // 4 | type | id=input-vaadin-text-field-7 | Antonio
    driver.findElement(By.id("input-vaadin-text-field-7")).sendKeys("Antonio");
    // 5 | click | css=vaadin-button:nth-child(2) | 
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("vaadin-button:nth-child(2)")));

    driver.findElement(By.cssSelector("vaadin-button:nth-child(2)")).click();
    // 6 | assertText | id=error-message-vaadin-password-field-6 | Password is required
    
    
    
    assertThat(driver.findElement(By.id("error-message-vaadin-password-field-6")).getText(), is("Password is required"));
  }
}
